apiVersion: v1
kind: Secret
metadata:
  name: todo-app-secret
type: Opaque
data:
  MYSQL_PASSWORD: bXlzZWNyZXRwYXNzd29yZA==
  MYSQL_USER: c29tZXVzZXI=
  MYSQL_ROOT_PASSWORD: bXlzZWNyZXRyb290cGFzc3dvcmQ=
