apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-app-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: todo-app-volume
  hostPath:
    path: "/mnt/data"
